PATH_GLOBAL_OBJ = ../../obj/global_obj/
PATH_GLOBAL     = ./
GLOBAL_SRC = $(wildcard $(PATH_GLOBAL)*.cpp)
GLOBAL_OBJ = $(patsubst $(PATH_GLOBAL)%.cpp, $(PATH_GLOBAL_OBJ)%.o, $(GLOBAL_SRC))

PATH_LIB = ../../libs/

CC = g++

FLAGS = -D _DEBUG -ggdb3 \
    -std=c++17 -O0 -Wall -Wextra -Weffc++ -Wc++14-compat        \
    -Wmissing-declarations -Wcast-qual -Wchar-subscripts  \
    -Wconversion -Wctor-dtor-privacy -Wempty-body -Wfloat-equal -Wformat-nonliteral -Wformat-security \
    -Wformat=2 -Winline -Wnon-virtual-dtor -Woverloaded-virtual \
    -Wpacked -Wpointer-arith -Winit-self -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo \
    -Wstrict-overflow=2 \
    -Wsuggest-override -Wswitch-default -Wswitch-enum -Wundef \
    -Wunreachable-code -Wunused -Wvariadic-macros \
    -Wno-missing-field-initializers -Wno-narrowing -Wno-old-style-cast -Wno-varargs \
    -Wstack-protector -fcheck-new -fsized-deallocation -fstack-protector -fstrict-overflow \
    -fno-omit-frame-pointer -Wlarger-than=8192 \
    -fPIE -Werror=vla -fsanitize=address,alignment,bool,bounds,enum,float-cast-overflow,float-divide-by-zero,integer-divide-by-zero,nonnull-attribute,null,return,returns-nonnull-attribute,shift,signed-integer-overflow,undefined,unreachable,vla-bound,vptr

LINK_FLAGS = -fsanitize=address,alignment,bool,bounds,enum,float-cast-overflow,float-divide-by-zero,integer-divide-by-zero,nonnull-attribute,null,return,returns-nonnull-attribute,shift,signed-integer-overflow,undefined,unreachable,vla-bound,vptr

$(PATH_LIB)libglobal.a: $(GLOBAL_OBJ)
	@ ar rvs $@ $(GLOBAL_OBJ)

$(PATH_GLOBAL_OBJ)%.o: $(PATH_GLOBAL)%.cpp
	@ $(CC) -c $< -o $@ $(FLAGS)

clean:
	@rm $(PATH_GLOBAL_OBJ)*.o
